version: '3'

services:
  ioc-container-dev:
    build:
      context: .
    ports:
      - "3000:3000"
    entrypoint: >-
      sh -c -x "npm install
      && npm install -g nodemon
      && nodemon index.js"
